"""Step 8 — compare the rebuild against the previous Project 9004 release.

Writes comparison_to_previous_release.md. The checks are ordered by what would actually
catch a defect, not by what is easy to report:

  1. shape, rows, participants
  2. column set diff, by dictionary category
  3. VALUE IDENTITY on the unchanged path — for proteomic blocks reused from verified
     *-to_merge.tab files, values on shared keys must be bit-identical. This is the
     check that proves the join changed and the data did not.
  4. per-block coverage and sparsity, old vs new
  5. derived-variable reconciliation
  6. lowput_ratio before/after (corrected — see the dictionary entry)
  7. genetics: GP2_nba_label vs p9001 ancestry agreement
  8. dictionary diff
"""

from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
NEW = os.path.join(HERE, "Project_9004_Unified_Emerging_Biomarkers.tab")
NEW_DICT = os.path.join(HERE, "Project_9004_Data_Dictionary.tab")
OLD = os.path.join(HERE, os.pardir, "Project_9004_Unified_Emerging_Biomarkers.tab")
OLD_DICT = os.path.join(HERE, os.pardir, "Project_9004_Data_Dictionary.tab")
REPORT = os.path.join(HERE, "comparison_to_previous_release.md")

PANELS = ["p277_CSF", "p282_CNS_CSF", "p282_Inflammation_CSF", "p288_CNS_plasma",
          "p288_Inflammation_plasma", "p293_olink_plasma", "p312_Inflammation_CSF",
          "p312_Inflammation_Plasma", "p312_Neuro_CSF", "p312_Neuro_Plasma",
          "p314_CSF", "p314_Plasma"]

DERIVED_PREFIXES = ("grp_", "tte_", "event_", "slope_", "CI_")
L: list[str] = []


def w(s: str = "") -> None:
    L.append(s)
    print(s, flush=True)


def head(path: str) -> list[str]:
    return pd.read_csv(path, sep="\t", nrows=0).columns.tolist()


def main() -> None:
    for p in (NEW, OLD):
        if not os.path.exists(p):
            sys.exit(f"missing {p}")

    nh, oh = head(NEW), head(OLD)
    ndd = pd.read_csv(NEW_DICT, sep="\t")
    odd = pd.read_csv(OLD_DICT, sep="\t")

    nk = pd.read_csv(NEW, sep="\t", usecols=["key", "PATNO", "EVENT_ID"], dtype=str)
    ok = pd.read_csv(OLD, sep="\t", usecols=["PATNO", "EVENT_ID"], dtype=str)
    ok["key"] = ok["PATNO"].str.strip() + "_" + ok["EVENT_ID"].str.strip()

    w("# Project 9004 — rebuild vs previous release")
    w()
    w("Generated by `build_step_8_compare.py`. The rebuild replaces the "
      "`PPMI_Proteomics_Data_Cut_INTERNAL_20251215` clinical scaffold with "
      "`PPMI_Curated_Data_Cut_Public_20260511` (sheet `20260511`), adds the `p9001_*` "
      "GP2 release-12 genetics block, and rebuilds every derived and PC column on top.")
    w()

    # --- 1. shape ----------------------------------------------------------
    w("## 1. Shape")
    w()
    w("| | previous | rebuild | change |")
    w("|---|---|---|---|")
    w(f"| Rows | {len(ok):,} | {len(nk):,} | {len(nk) - len(ok):+,} |")
    w(f"| Columns | {len(oh):,} | {len(nh):,} | {len(nh) - len(oh):+,} |")
    w(f"| Participants | {ok.PATNO.nunique():,} | {nk.PATNO.nunique():,} | "
      f"{nk.PATNO.nunique() - ok.PATNO.nunique():+,} |")
    w(f"| Dictionary entries | {len(odd):,} | {len(ndd):,} | {len(ndd) - len(odd):+,} |")
    w()
    okeys, nkeys = set(ok["key"]), set(nk["key"])
    w(f"- Previous keys retained in the rebuild: **{len(okeys & nkeys):,} of {len(okeys):,}** "
      f"({len(okeys & nkeys) / len(okeys) * 100:.2f}%)")
    w(f"- Previous keys absent from the rebuild: **{len(okeys - nkeys):,}**")
    w(f"- New keys added: **{len(nkeys - okeys):,}**")
    w(f"- Previous participants absent from the rebuild: **{len(set(ok.PATNO) - set(nk.PATNO)):,}**")
    w()

    # --- 2. column diff ----------------------------------------------------
    added, removed = [c for c in nh if c not in set(oh)], [c for c in oh if c not in set(nh)]
    w("## 2. Columns added and removed")
    w()
    cat_n = dict(zip(ndd.Variable, ndd.Category))
    cat_o = dict(zip(odd.Variable, odd.Category))
    w("| Category | added | removed |")
    w("|---|---|---|")
    cats = sorted({cat_n.get(c, "?") for c in added} | {cat_o.get(c, "?") for c in removed})
    for c in cats:
        a = sum(1 for x in added if cat_n.get(x, "?") == c)
        r = sum(1 for x in removed if cat_o.get(x, "?") == c)
        w(f"| {c} | {a:,} | {r:,} |")
    w(f"| **total** | **{len(added):,}** | **{len(removed):,}** |")
    w()
    w("Removed, grouped by what they were:")
    w()
    groups = {
        "Assay-availability / near-visit indicators (NULISA_*, Olink_*)":
            [c for c in removed if c.startswith(("NULISA_", "Olink_"))],
        "SAA replicate/detail columns":
            [c for c in removed if any(c.startswith(p) for p in
             ("Fmax_", "TTT_", "AUC_", "TSmax_", "SLOPEMax_", "T50_", "SLOPE_", "CSFSAA"))],
        "DATSCAN_* series (curated cut carries only MIA_*)":
            [c for c in removed if c.startswith(("DATSCAN_", "con_", "ips_", "mean_"))
             or c == "lowput_expected"],
        "All_Combined PC blocks (deferred to harmonized data)":
            [c for c in removed if c.startswith("All_Combined")],
    }
    accounted: set = set()
    for label, cols in groups.items():
        if cols:
            w(f"- **{label}** — {len(cols)}")
            accounted |= set(cols)
    rest = [c for c in removed if c not in accounted]
    if rest:
        w(f"- **Other** — {len(rest)}: {rest}")
    w()

    # --- 3. value identity on the unchanged path ---------------------------
    w("## 3. Value identity on the unchanged path")
    w()
    w("Proteomic blocks are reused from the same verified `*-to_merge.tab` files, so on "
      "keys present in both releases every analyte value must be **bit-identical**. A "
      "difference here would mean the join changed the data, not the scaffold.")
    w()
    w("| Panel | analytes checked | identical | differing | max abs diff |")
    w("|---|---|---|---|---|")
    shared = sorted(okeys & nkeys)
    rng = np.random.default_rng(0)
    total_diff = 0
    for p in PANELS:
        cols = [c for c in nh if c.startswith(p + "_") and "earliest_visit_PC" not in c
                and "PLATE_ID" not in c and c in set(oh)]
        if not cols:
            w(f"| {p} | 0 | — | — | — |")
            continue
        probe = sorted(rng.choice(cols, size=min(150, len(cols)), replace=False).tolist())
        a = pd.read_csv(NEW, sep="\t", usecols=["key"] + probe, dtype={"key": str}).set_index("key")
        b = pd.read_csv(OLD, sep="\t", usecols=["PATNO", "EVENT_ID"] + probe, dtype=str)
        b.index = b["PATNO"].str.strip() + "_" + b["EVENT_ID"].str.strip()
        b = b.drop(columns=["PATNO", "EVENT_ID"]).astype(float)
        a, b = a.reindex(shared), b.reindex(shared)
        same = diff = 0
        mx = 0.0
        for c in probe:
            x, y = a[c], b[c]
            m = x.notna() & y.notna()
            if m.sum() == 0:
                same += 1
                continue
            d = float((x[m] - y[m]).abs().max())
            if d <= 1e-9:
                same += 1
            else:
                diff += 1
                mx = max(mx, d)
        total_diff += diff
        w(f"| {p} | {len(probe)} | {same} | {diff} | {mx:.2e} |")
    w()
    w(f"**{'PASS' if total_diff == 0 else 'FAIL'}** — "
      f"{'every sampled analyte is identical on shared keys.' if total_diff == 0 else f'{total_diff} analytes differ.'}")
    w()

    # --- 4. coverage -------------------------------------------------------
    w("## 4. Per-block coverage")
    w()
    cov = pd.read_csv(sorted(__import__("glob").glob(
        os.path.join(HERE, "build_intermediates", "block_coverage-*.tab")))[-1], sep="\t")
    w("| Block | vendor samples | matched, previous cut | matched, new cut | gain |")
    w("|---|---|---|---|---|")
    for _, r in cov.iterrows():
        w(f"| {r.block} | {r.vendor_samples:,} | {r.matched_old_cut:,} ({r.pct_old}%) | "
          f"{r.matched_new_cut:,} ({r.pct_new}%) | {r.gain:+,} |")
    w(f"| **total** | | **{cov.matched_old_cut.sum():,}** | "
      f"**{cov.matched_new_cut.sum():,}** | **{cov.gain.sum():+,}** |")
    w()
    w("Sparsity percentages rise even where a block gained samples, because the scaffold "
      "grew from 10,354 to 19,450 rows. Absolute data is up; the denominator is up more.")
    w()

    # --- 5. derived --------------------------------------------------------
    w("## 5. Derived variables")
    w()
    dcols = [c for c in nh if c.startswith(DERIVED_PREFIXES) and c in set(oh)]
    a = pd.read_csv(NEW, sep="\t", usecols=["key", "PATNO"] + dcols, dtype={"key": str, "PATNO": str})
    b = pd.read_csv(OLD, sep="\t", usecols=["PATNO"] + dcols, dtype={"PATNO": str})
    w("| Variable | previous n | rebuild n | previous positives | rebuild positives |")
    w("|---|---|---|---|---|")
    for c in dcols:
        x, y = pd.to_numeric(a[c], errors="coerce"), pd.to_numeric(b[c], errors="coerce")
        w(f"| {c} | {y.notna().sum():,} | {x.notna().sum():,} | "
          f"{int((y == 1).sum()):,} | {int((x == 1).sum()):,} |")
    w()
    w("Every group grows with the participant expansion. `grp_NMC_*` additionally changed "
      "definition: multi-gene carriers are now excluded by gene-token test rather than by "
      "exact-matching the single label `LRRK2 + GBA`, because the refreshed cut introduces "
      "labels such as `LRRK2 + GBA + Normosmic` that the old rule would have counted as "
      "clean single-gene carriers in several groups at once.")
    w()
    w("### The non-manifesting-carrier groups become usable")
    w()
    w("The largest proportional change in the table is `grp_NMC_LRRK2` (36 -> 1,534 "
      "positive rows). It is real, and it is the most consequential clinical consequence "
      "of the scaffold refresh. Prodromal-cohort composition at baseline:")
    w()
    sg = pd.read_csv(NEW, sep="\t", usecols=["EVENT_ID", "COHORT", "subgroup"], dtype=str)
    sgo = pd.read_csv(OLD, sep="\t", usecols=["EVENT_ID", "COHORT", "subgroup"], dtype=str)
    w("| | previous | rebuild |")
    w("|---|---|---|")
    rows = []
    for lab, d in (("previous", sgo), ("rebuild", sg)):
        b = d[(d.EVENT_ID == "BL") & (d.COHORT == "4")]
        rows.append((len(b), int(b.subgroup.str.contains("LRRK2", na=False).sum()),
                     int(b.subgroup.str.contains("GBA", na=False).sum())))
    w(f"| Prodromal participants at BL | {rows[0][0]:,} | {rows[1][0]:,} |")
    w(f"| — carrying LRRK2 | {rows[0][1]:,} | {rows[1][1]:,} |")
    w(f"| — carrying GBA | {rows[0][2]:,} | {rows[1][2]:,} |")
    w()
    w("This is the **enriched LRRK2 / GBA genetic cohort** arriving. The previous scaffold "
      "was a proteomics-selected subset whose prodromal arm was almost entirely Hyposmia "
      "and RBD, with the genetic enrichment cohort essentially absent; the NMC contrasts "
      "existed as columns but had too few participants to fit. They are now analyzable.")
    w()
    w("Two consequences worth carrying into phase 2. First, the enrichment cohort is "
      "**not** proteomically assayed at the same rate as the rest of the study, so a "
      "larger `grp_NMC_*` N does not translate one-for-one into usable proteomic N — "
      "check per-block coverage within these groups before powering anything on them. "
      "Second, adding an enriched carrier cohort shifts the genetic composition of every "
      "contrast that does not condition on carrier status, `grp_HC_vs_Prodromal` most of "
      "all, so previous and rebuild effect sizes for those runs are not like-for-like.")
    w()

    # --- 6. lowput_ratio ---------------------------------------------------
    w("## 6. `lowput_ratio` — corrected")
    w()
    an = pd.read_csv(NEW, sep="\t", usecols=["lowput_ratio", "slope_lowput_ratio",
                                             "MIA_PUTAMEN_L", "MIA_PUTAMEN_R"])
    ao = pd.read_csv(OLD, sep="\t", usecols=["lowput_ratio", "slope_lowput_ratio",
                                             "DATSCAN_PUTAMEN_L", "DATSCAN_PUTAMEN_R"])
    on = np.minimum(an.MIA_PUTAMEN_L, an.MIA_PUTAMEN_R)
    oo = np.minimum(ao.DATSCAN_PUTAMEN_L, ao.DATSCAN_PUTAMEN_R)
    mn, mo = an.lowput_ratio.notna() & on.notna(), ao.lowput_ratio.notna() & oo.notna()
    w("| | previous | rebuild |")
    w("|---|---|---|")
    w(f"| n | {ao.lowput_ratio.notna().sum():,} | {an.lowput_ratio.notna().sum():,} |")
    w(f"| median | {ao.lowput_ratio.median():.3f} | {an.lowput_ratio.median():.3f} |")
    w(f"| % below 0.75 (DaT-positive) | {(ao.lowput_ratio < 0.75).sum() / ao.lowput_ratio.notna().sum() * 100:.1f}% "
      f"| {(an.lowput_ratio < 0.75).sum() / an.lowput_ratio.notna().sum() * 100:.1f}% |")
    w(f"| corr with observed min-putamen SBR | {oo[mo].corr(ao.lowput_ratio[mo]):.3f} "
      f"| {on[mn].corr(an.lowput_ratio[mn]):.3f} |")
    w(f"| slope sd (between-participant spread) | {ao.slope_lowput_ratio.std():.4f} "
      f"| {an.slope_lowput_ratio.std():.4f} |")
    w()
    w("The previous variable carried essentially no imaging signal — see the "
      "`lowput_ratio` entry in the data dictionary for the full derivation and evidence. "
      "**Any prior result using `lowput_ratio` or `slope_lowput_ratio` should be re-read.**")
    w()

    # --- 7. genetics -------------------------------------------------------
    w("## 7. Genetics — GP2 and p9001 side by side")
    w()
    g = pd.read_csv(NEW, sep="\t", usecols=["PATNO", "GP2_nba_label", "p9001_Genetic_PRS_InfPop"],
                    dtype={"PATNO": str}).drop_duplicates("PATNO")
    w(f"- Participants with `GP2_nba_label`: **{g.GP2_nba_label.notna().sum():,}**")
    w(f"- Participants with `p9001_Genetic_PRS_InfPop`: **{g.p9001_Genetic_PRS_InfPop.notna().sum():,}**")
    both = g.GP2_nba_label.notna() & g.p9001_Genetic_PRS_InfPop.notna()
    agree = (g.loc[both, "GP2_nba_label"] == g.loc[both, "p9001_Genetic_PRS_InfPop"]).sum()
    w(f"- Both present: **{both.sum():,}**, of which the labels agree on "
      f"**{agree:,}** ({agree / both.sum() * 100:.2f}%)")
    w()
    dis = g[both & (g.GP2_nba_label != g.p9001_Genetic_PRS_InfPop)]
    if len(dis):
        w("Disagreements:")
        w()
        w("| GP2_nba_label | p9001 InfPop | n |")
        w("|---|---|---|")
        for (x, y), n in dis.groupby(["GP2_nba_label", "p9001_Genetic_PRS_InfPop"]).size().sort_values(
                ascending=False).head(12).items():
            w(f"| {x} | {y} | {n} |")
        w()
    w("Analysis strata remain defined on `GP2_nba_label`; adopting the p9001 label is an "
      "analysis decision left for phase 2.")
    w()

    # --- 8. dictionary -----------------------------------------------------
    w("## 8. Dictionary")
    w()
    w(f"- Entries: {len(odd):,} -> {len(ndd):,}")
    w(f"- 1:1 with the dataset: **{'yes' if len(ndd) == len(nh) and list(ndd.Variable) == nh else 'NO'}**")
    recat = [(v, cat_o[v], cat_n[v]) for v in set(cat_o) & set(cat_n) if cat_o[v] != cat_n[v]]
    w(f"- Entries whose Category changed: **{len(recat)}**")
    if recat:
        w()
        w("| Variable | previous | rebuild |")
        w("|---|---|---|")
        for v, a_, b_ in sorted(recat)[:25]:
            w(f"| {v} | {a_} | {b_} |")
    w()

    with open(REPORT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"\nwrote {REPORT}")


if __name__ == "__main__":
    sys.exit(main())
